class Customer(object):
    """generated by chatGPT. A class that can be created by a dictionary.
    If printed, returns all its attributes.
    """
    def __init__(self, data):
        self.__dict__ = data

    def __str__(self):
        attrs = []
        for key, value in vars(self).items():
            if isinstance(value, dict):
                # value is possibly a nested dictionary, so we recursively call __str__
                value = Customer(value).__str__()
            attrs.append(f"{key}: {value}")
        return "\n".join(attrs)